---
- hosts: all
  gather_facts: true
  become: true
  vars:
    - host_domain: "lab.home"
  tasks:
  - hostname: name={{ inventory_hostname | lower }}.{{ host_domain | lower }}
  - file: src=/usr/share/zoneinfo/Australia/Perth dest=/etc/localtime state=link force=yes
  - yum: name=libselinux-python state=present update_cache=yes
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 7
  - selinux: policy=targeted state=permissive

- import_playbook: site.yml
