#!/bin/bash

#SBATCH -N 2
#SBATCH --ntasks-per-node=2
#SBATCH -p batch
#SBATCH --exclusive
#SBATCH --time=01:00:00
#SBATCH -o slurm.%N.%j.out
#SBATCH -e slurm.%N.%j.err

module load mpi/openmpi-x86_64

mpiexec mpiexample > mpiexample.out
